### ISSUE TITLE
0.2.3 - Uncaught TypeError: Cannot read property '0' of null FileSystem.isAbsolutePath

### ISSUE THREAD

**Issue by mezpahlan** [mitchellsimoens/brackets-sencha#6]
Hello again.

Running Windows version of Brackets Release 1.3 build 1.3.0-16022 and 0.2.3 of the Sencha extension I run into the follow error whilst trying to run any of the Sencha commands.

    Uncaught TypeError: Cannot read property '0' of null  /filesystem/FileSystem.js:464
    FileSystem.isAbsolutePath    /filesystem/FileSystem.js:490
    FileSystem._normalizePath    /filesystem/FileSystem.js:558 
    FileSystem._getEntryForPath    /filesystem/FileSystem.js:588 
    FileSystem.getDirectoryForPath    /filesystem/FileSystem.js:980
    (anonymous function)    (program):224 
    Sencha.define.findAppDir    (program):258 
    (anonymous function)    /filesystem/Directory.js:122 
    _applyAllCallbacks    /filesystem/Directory.js:217 
    (anonymous function)    /filesystem/impls/appshell/AppshellFileSystem.js:304
    (anonymous function)    /filesystem/impls/appshell/AppshellFileSystem.js:244 
    (anonymous function)    appshell:303 
   
Is this a problem with my set up or something else? Note: I can run the equivalent Sencha commands using the command line.

**Comment by mitchellsimoens** [comment]
What file are you running this on? Is this file within the application? Is it within a Cmd package?

I just tested on a Windows 8 box and the extension is working for me. The error is on a line that is trying to find the application directory that has a .sencha directory within it but it cannot find the directory.

**Comment by mezpahlan** [comment]
I do beg your pardon, it wasn't a file within my application. However when I do run `app watch` or similar on a file within my application (i.e. index.html or app.js) I now get the following error.

```
Uncaught Error: Paths must be absolute: '::{20D04FE0-3AEA-1069-A2D8-08002B30309D}/5.1.0.26/sencha'    /filesystem/FileSystem.js:491 
```

**Comment by mitchellsimoens** [comment]
Try setting the config for the path to cmd. Go to Edit -> Sencha Preferences and the first config should be a path to where your Cmd installs are located.

**Comment by mezpahlan** [comment]
Hmm, how strange. It now has a weird string for the Sencha Cmd location `::{20D04FE0-3AEA-1069-A2D8-08002B30309D}`. I certainly didn't set it to that. Furthermore it won't let me change it. I can select the correct folder using the folder picker, but it doesn't make the change.

Possibly a bug in my Brackets installation?

**Comment by mitchellsimoens** [comment]
I found a bug with the cmd path selection. I just pushed a 0.2.4 update to fix that.

**Comment by mezpahlan** [comment]
Thanks, that has fixed it for me.
